name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Generate tests
      run: test-gen/gen.py > src/pyca-test-vectors.in
    - name: Run tests
      run: cargo test --verbose
